services:
  chatterer:
    build: .
    restart: always
    networks:
      - traefik
    env_file:
      - stack.env
    environment:
      - BOT__ROUTE=/telegram/chatterer
      - BOT__PERSISTENCE_PATH=/data
    volumes:
      - /opt/chatterer-data:/data
    labels:
      - "traefik.enable=true"
      - "route=/telegram/chatterer"
      - "traefik.http.routers.chatterer.entrypoints=telegram"
      - "traefik.http.routers.chatterer.tls.certresolver=letsencrypt"
      - "traefik.http.services.chatterer.loadbalancer.server.port=8443"

networks:
  traefik:
    external: true
