services:
  chatterer:
    build: .
    env_file:
      - .env
    environment:
      - BOT__KEY_PATH=/ssl/private.key
      - BOT__CERT_PATH=/ssl/cert.pem
      - BOT__PERSISTENCE_PATH=/data
    volumes:
      - ./ssl:/ssl
      - ./data:/data
    ports:
      - "8443:8443"
