services:
  chatterer:
    build: .
    networks:
      - traefik
    env_file:
      - .env
    environment:
      - BOT__ROUTE=/telegram/chatterer
      - BOT__PERSISTENCE_PATH=/data
    volumes:
      - ./ssl:/ssl
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatterer.rule=PathPrefix(`/telegram/chatterer`)"
      - "traefik.http.routers.chatterer.entrypoints=telegram"
      - "traefik.http.routers.chatterer.tls.certresolver=letsencrypt"
      - "traefik.http.services.chatterer.loadbalancer.server.port=8443"

networks:
  traefik:
    external: true